create extension if not exists pgcrypto;

do $$ begin create type public.app_role as enum ('admin','caller'); exception when duplicate_object then null; end $$;
do $$ begin create type public.campaign_status as enum ('draft','active','completed'); exception when duplicate_object then null; end $$;
do $$ begin create type public.calling_status as enum ('not_called','connected','dnp','busy','switched_off','wrong_number','interested','not_interested','follow_up','opd_booked','call_back'); exception when duplicate_object then null; end $$;
do $$ begin create type public.opd_status as enum ('not_discussed','interested','opd_recommended','opd_booked','opd_completed','no_show','cancelled'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role public.app_role not null default 'caller',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.lead_sources (
  id uuid primary key default gen_random_uuid(), name text unique not null,
  is_active boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists public.campaigns (
  id uuid primary key default gen_random_uuid(), name text not null, campaign_date date not null,
  status public.campaign_status not null default 'draft', location text, notes text,
  created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(), lead_number bigint generated by default as identity unique,
  patient_name text not null, phone text not null, alternate_phone text, source_id uuid not null references public.lead_sources(id),
  campaign_id uuid not null references public.campaigns(id), assigned_to uuid references public.profiles(id),
  calling_status public.calling_status not null default 'not_called', opd_status public.opd_status not null default 'not_discussed',
  follow_up_date date, follow_up_time time, remarks text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.call_logs (
  id uuid primary key default gen_random_uuid(), lead_id uuid not null references public.leads(id) on delete cascade,
  caller_id uuid not null references public.profiles(id), calling_status public.calling_status not null, remarks text,
  called_at timestamptz not null default now()
);
create table if not exists public.follow_ups (
  id uuid primary key default gen_random_uuid(), lead_id uuid not null references public.leads(id) on delete cascade,
  assigned_to uuid references public.profiles(id), follow_up_date date not null, follow_up_time time,
  status text not null default 'open', notes text, created_at timestamptz not null default now(), completed_at timestamptz
);
create table if not exists public.opd_bookings (
  id uuid primary key default gen_random_uuid(), lead_id uuid not null references public.leads(id) on delete cascade,
  booking_date date, doctor_name text, department text, hospital_name text, booking_status text not null default 'booked',
  notes text, created_by uuid references public.profiles(id), created_at timestamptz not null default now()
);
create table if not exists public.lead_assignments (
  id uuid primary key default gen_random_uuid(), lead_id uuid not null references public.leads(id) on delete cascade,
  assigned_to uuid not null references public.profiles(id), assigned_by uuid references public.profiles(id), assigned_at timestamptz not null default now()
);
create table if not exists public.import_batches (
  id uuid primary key default gen_random_uuid(), source_id uuid references public.lead_sources(id), campaign_id uuid references public.campaigns(id),
  imported_by uuid references public.profiles(id), file_name text, row_count int default 0, inserted_count int default 0,
  duplicate_count int default 0, created_at timestamptz not null default now()
);
create table if not exists public.activity_logs (
  id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id), action text not null,
  entity_type text, entity_id uuid, metadata jsonb, created_at timestamptz not null default now()
);
create index if not exists leads_phone_idx on public.leads(phone);
create index if not exists leads_campaign_idx on public.leads(campaign_id);
create index if not exists leads_assigned_idx on public.leads(assigned_to);
create index if not exists leads_status_idx on public.leads(calling_status);

insert into public.lead_sources(name) values ('Meta Leads'),('WhatsApp CTA'),('RCS'),('Hospital Dump'),('Other') on conflict(name) do nothing;

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin' and is_active); $$;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin insert into public.profiles(id,full_name,role) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1)),'caller') on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists leads_touch_updated on public.leads; create trigger leads_touch_updated before update on public.leads for each row execute procedure public.touch_updated_at();
drop trigger if exists campaigns_touch_updated on public.campaigns; create trigger campaigns_touch_updated before update on public.campaigns for each row execute procedure public.touch_updated_at();

alter table public.profiles enable row level security;
alter table public.lead_sources enable row level security;
alter table public.campaigns enable row level security;
alter table public.leads enable row level security;
alter table public.call_logs enable row level security;
alter table public.follow_ups enable row level security;
alter table public.opd_bookings enable row level security;
alter table public.lead_assignments enable row level security;
alter table public.import_batches enable row level security;
alter table public.activity_logs enable row level security;

create policy profiles_select on public.profiles for select to authenticated using (id=auth.uid() or public.is_admin());
create policy profiles_admin_all on public.profiles for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy sources_select on public.lead_sources for select to authenticated using(true);
create policy sources_admin_all on public.lead_sources for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy campaigns_select on public.campaigns for select to authenticated using(true);
create policy campaigns_admin_all on public.campaigns for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy leads_select on public.leads for select to authenticated using(public.is_admin() or assigned_to=auth.uid());
create policy leads_admin_insert on public.leads for insert to authenticated with check(public.is_admin());
create policy leads_update on public.leads for update to authenticated using(public.is_admin() or assigned_to=auth.uid()) with check(public.is_admin() or assigned_to=auth.uid());
create policy leads_admin_delete on public.leads for delete to authenticated using(public.is_admin());
create policy calls_select on public.call_logs for select to authenticated using(public.is_admin() or caller_id=auth.uid());
create policy calls_insert on public.call_logs for insert to authenticated with check(public.is_admin() or caller_id=auth.uid());
create policy followups_select on public.follow_ups for select to authenticated using(public.is_admin() or assigned_to=auth.uid());
create policy followups_write on public.follow_ups for all to authenticated using(public.is_admin() or assigned_to=auth.uid()) with check(public.is_admin() or assigned_to=auth.uid());
create policy opd_select on public.opd_bookings for select to authenticated using(public.is_admin() or created_by=auth.uid() or exists(select 1 from public.leads l where l.id=lead_id and l.assigned_to=auth.uid()));
create policy opd_write on public.opd_bookings for all to authenticated using(public.is_admin() or created_by=auth.uid()) with check(public.is_admin() or created_by=auth.uid());
create policy assignments_select on public.lead_assignments for select to authenticated using(public.is_admin() or assigned_to=auth.uid());
create policy assignments_admin_insert on public.lead_assignments for insert to authenticated with check(public.is_admin());
create policy imports_admin_all on public.import_batches for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy activity_admin_select on public.activity_logs for select to authenticated using(public.is_admin());
create policy activity_insert on public.activity_logs for insert to authenticated with check(public.is_admin() or user_id=auth.uid());

-- After creating your Admin user in Auth, run:
-- update public.profiles set full_name='Your Name', role='admin' where id='YOUR-AUTH-USER-UUID';
